# SMCBlacksmith Configuration
version: 1.0.0

# Language file to use from lang folder
language: en_US.yml

furnaces:
  # How often furnaces tick (in server ticks, 20 = 1 second)
  ticks: 20
  # Cooldown for bellows usage in ticks
  bellows_cooldown: 20

blacksmithing:
  # Format for smithed item lore, %s is player name
  name_format: "Smithed by %s"